spring.application.name=ProyectoUniEventos

spring.data.mongodb.uri=mongodb://localhost:27017/UniEventos

server.port=8081
spring.data.mongodb.host=
spring.data.mongodb.port=

# Nivel de logging general
logging.level.root=DEBUG

# Para ver todos los logs de la aplicación
logging.level.com.example.proyectounieventos=DEBUG

# Salida de logs en la consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n